<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AndroidPC" failures="2" tests="4" name="com.tms.tests.CourseRunPageTest" time="126.549" errors="0" timestamp="2021-08-02T18:46:50 IST" skipped="0">
  <testcase classname="com.tms.tests.CourseRunPageTest" name="CompletedCourseRunRecordTest" time="34.324">
    <failure message="expected [Courses Run View - TMS] but found [All Completed Course Runs - TMS]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Courses Run View - TMS] but found [All Completed Course Runs - TMS]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.tms.tests.CourseRunPageTest.CompletedCourseRunRecordTest(CourseRunPageTest.java:109)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </failure>
  </testcase> <!-- CompletedCourseRunRecordTest -->
  <system-out/>
  <testcase classname="com.tms.tests.CourseRunPageTest" name="ClickonCompletedStudentListfromAllCourseRunRecordTest" time="32.054"/>
  <system-out/>
  <testcase classname="com.tms.tests.CourseRunPageTest" name="ClickonCompletedAssessmentAndAttendancefromAllCourseRunRecordTest" time="25.502">
    <failure message="expected [Attendance Assessment List - Course Run - TMS] but found [All Completed Course Runs - TMS]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Attendance Assessment List - Course Run - TMS] but found [All Completed Course Runs - TMS]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.tms.tests.CourseRunPageTest.ClickonCompletedAssessmentAndAttendancefromAllCourseRunRecordTest(CourseRunPageTest.java:135)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </failure>
  </testcase> <!-- ClickonCompletedAssessmentAndAttendancefromAllCourseRunRecordTest -->
  <system-out/>
  <testcase classname="com.tms.tests.CourseRunPageTest" name="EditCompletedCourseRunRecordTest" time="34.669"/>
  <system-out/>
</testsuite> <!-- com.tms.tests.CourseRunPageTest -->
